version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dummy_messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  server_1:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn server.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./.env.example:/app/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  server_2:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn server.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
      - ./.env.example:/app/.env
    depends_on:
      - db
    ports:
      - "8001:8001"


volumes:
  pg_data:
